// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viegard.Persistence.Postgres;

#nullable disable

namespace Viegard.Persistence.Postgres.Migrations
{
    [DbContext(typeof(ViegardDbContext))]
    [Migration("20260825224059_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActionRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_id");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RollbackJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("rollback_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AuditRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<Guid?>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ClassificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ClassifierId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classifier_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_json");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons_json");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer")
                        .HasColumnName("subject_kind");

                    b.Property<double?>("Uncertainty")
                        .HasColumnType("double precision")
                        .HasColumnName("uncertainty");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SubjectId");

                    b.ToTable("classifications", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.CorrectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<string>("CorrectedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corrected_by");

                    b.Property<string>("CorrectedCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corrected_category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("corrections", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.DecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("guardrails_json");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.IncidentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_key");

                    b.Property<string>("EventIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_ids_json");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey", "State");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.NormalizedEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entities_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("RawObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_observation_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RawObservationId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueCounterRow", b =>
                {
                    b.Property<string>("QueueName")
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.Property<long>("Abandoned")
                        .HasColumnType("bigint")
                        .HasColumnName("abandoned");

                    b.Property<long>("Completed")
                        .HasColumnType("bigint")
                        .HasColumnName("completed");

                    b.Property<long>("Enqueued")
                        .HasColumnType("bigint")
                        .HasColumnName("enqueued");

                    b.HasKey("QueueName");

                    b.ToTable("queue_counters", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueMessageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("DeadLettered")
                        .HasColumnType("boolean")
                        .HasColumnName("dead_lettered");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_count");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leased_until");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.HasKey("Id");

                    b.HasIndex("QueueName", "DeadLettered", "LeasedUntil", "Id");

                    b.ToTable("queue_messages", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueTelemetryRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("QueueName")
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("DeadLetterCount")
                        .HasColumnType("integer")
                        .HasColumnName("dead_letter_count");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<int>("InFlight")
                        .HasColumnType("integer")
                        .HasColumnName("in_flight");

                    b.Property<DateTimeOffset?>("OldestPendingEnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oldest_pending_enqueued_at");

                    b.Property<long>("TotalAbandoned")
                        .HasColumnType("bigint")
                        .HasColumnName("total_abandoned");

                    b.Property<long>("TotalCompleted")
                        .HasColumnType("bigint")
                        .HasColumnName("total_completed");

                    b.Property<long>("TotalEnqueued")
                        .HasColumnType("bigint")
                        .HasColumnName("total_enqueued");

                    b.HasKey("InstanceId", "QueueName");

                    b.ToTable("queue_telemetry", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.RawObservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IngestOffset")
                        .HasColumnType("text")
                        .HasColumnName("ingest_offset");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PayloadReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_reference");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("PayloadReference")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("raw_observations", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.SourceOffsetRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("SourceId", "Key");

                    b.ToTable("source_offsets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
