// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viegard.Persistence.Postgres;

#nullable disable

namespace Viegard.Persistence.Postgres.Migrations
{
    [DbContext(typeof(ViegardDbContext))]
    [Migration("20260917045129_AddListFilterIndexes")]
    partial class AddListFilterIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActionProviderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey")
                        .IsUnique();

                    b.ToTable("action_providers", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActionRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_id");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("text")
                        .HasColumnName("results_json");

                    b.Property<string>("RollbackJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("rollback_json");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RequestedAt");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActiveBanRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.HasKey("Id");

                    b.HasIndex("Ip")
                        .IsUnique();

                    b.ToTable("active_bans", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminRecoveryCodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("admin_recovery_codes", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminSessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("IpBindingMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_binding_mode");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("StepUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("step_up_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAt");

                    b.HasIndex("IdleExpiresAt");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("UserId");

                    b.ToTable("admin_sessions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminTotpSecretRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<long?>("LastAcceptedStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_accepted_step");

                    b.Property<string>("SecretBase32")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_base32");

                    b.HasKey("UserId");

                    b.ToTable("admin_totp_secrets", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminUserPreferencesRow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("PageSize")
                        .HasColumnType("integer")
                        .HasColumnName("page_size");

                    b.Property<int>("StatusRefreshSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("status_refresh_seconds");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("admin_user_preferences", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminUserRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("TotpEnrolled")
                        .HasColumnType("boolean")
                        .HasColumnName("totp_enrolled");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminWebAuthnCredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Aaguid")
                        .HasColumnType("uuid")
                        .HasColumnName("aaguid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<string>("Transports")
                        .HasColumnType("text")
                        .HasColumnName("transports");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("admin_webauthn_credentials", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AuditRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("action_id");

                    b.Property<Guid?>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Stage", "Id")
                        .IsDescending(false, true);

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ClassificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("ClassifierId")
                        .HasColumnType("integer")
                        .HasColumnName("classifier_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ModelJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_json");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reasons_json");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text")
                        .HasColumnName("recommended_action");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer")
                        .HasColumnName("subject_kind");

                    b.Property<double?>("Uncertainty")
                        .HasColumnType("double precision")
                        .HasColumnName("uncertainty");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SubjectId");

                    b.ToTable("classifications", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ClassifierRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassifierKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classifier_key");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassifierKey")
                        .IsUnique();

                    b.ToTable("classifiers", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.CorrectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<string>("CorrectedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corrected_by");

                    b.Property<string>("CorrectedCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corrected_category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("corrections", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.CustomSignatureRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalPatternsJson")
                        .HasColumnType("text")
                        .HasColumnName("additional_patterns_json");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<double>("EvidenceWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("evidence_weight");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer")
                        .HasColumnName("match_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pattern");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("custom_signatures", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.DecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("guardrails_json");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("PolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("policy_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<int?>("ReviewOutcome")
                        .HasColumnType("integer")
                        .HasColumnName("review_outcome");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PolicyId");

                    b.HasIndex("Outcome", "Id")
                        .IsDescending(false, true);

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.HostUpgradeCommandRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("Target")
                        .IsUnique()
                        .HasFilter("status IN (0, 1)");

                    b.HasIndex("Target", "FinishedAt");

                    b.HasIndex("Target", "Status", "RequestedAt");

                    b.ToTable("host_upgrade_commands", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.IncidentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_key");

                    b.Property<string>("EventIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_ids_json");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence_json");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey", "State");

                    b.HasIndex("State", "Id")
                        .IsDescending(false, true);

                    b.HasIndex("WindowStart", "State");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.IngestionFilterRow", b =>
                {
                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("EventKind")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_kind");

                    b.Property<bool>("Suppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("suppressed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("SourceType", "EventKind");

                    b.ToTable("ingestion_filters", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.InstanceRegistrationRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text")
                        .HasColumnName("commit_sha");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_name");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roles");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UpgradeTarget")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("upgrade_target");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("InstanceId");

                    b.ToTable("instance_registry", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.MikroTikRouterRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_ciphertext");

                    b.Property<string>("PinnedCertificateSha256")
                        .HasColumnType("text")
                        .HasColumnName("pinned_cert_sha256");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<string>("TransportMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_mode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("mikrotik_routers", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.NormalizedEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entities_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("RawObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_observation_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RawObservationId");

                    b.HasIndex("SourceId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.PolicyRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_key");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.HasKey("Id");

                    b.HasIndex("PolicyKey", "PolicyVersion")
                        .IsUnique();

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.PolicyThresholdSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<double>("ActionConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("action_confidence");

                    b.Property<int>("ActionMinSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("action_min_severity");

                    b.Property<double>("ReviewConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("review_confidence");

                    b.Property<int>("RowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("policy_threshold_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_policy_threshold_settings_fixed_id", "id = 1");
                        });
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueCounterRow", b =>
                {
                    b.Property<string>("QueueName")
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.Property<long>("Abandoned")
                        .HasColumnType("bigint")
                        .HasColumnName("abandoned");

                    b.Property<long>("Completed")
                        .HasColumnType("bigint")
                        .HasColumnName("completed");

                    b.Property<long>("Enqueued")
                        .HasColumnType("bigint")
                        .HasColumnName("enqueued");

                    b.HasKey("QueueName");

                    b.ToTable("queue_counters", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueMessageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("DeadLettered")
                        .HasColumnType("boolean")
                        .HasColumnName("dead_lettered");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_count");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leased_until");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.HasKey("Id");

                    b.HasIndex("DeadLettered", "EnqueuedAt");

                    b.HasIndex("QueueName", "DeadLettered", "LeasedUntil", "Id");

                    b.ToTable("queue_messages", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueTelemetryRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("QueueName")
                        .HasColumnType("text")
                        .HasColumnName("queue_name");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("DeadLetterCount")
                        .HasColumnType("integer")
                        .HasColumnName("dead_letter_count");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<int>("InFlight")
                        .HasColumnType("integer")
                        .HasColumnName("in_flight");

                    b.Property<DateTimeOffset?>("OldestPendingEnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("oldest_pending_enqueued_at");

                    b.Property<long>("TotalAbandoned")
                        .HasColumnType("bigint")
                        .HasColumnName("total_abandoned");

                    b.Property<long>("TotalCompleted")
                        .HasColumnType("bigint")
                        .HasColumnName("total_completed");

                    b.Property<long>("TotalEnqueued")
                        .HasColumnType("bigint")
                        .HasColumnName("total_enqueued");

                    b.HasKey("InstanceId", "QueueName");

                    b.ToTable("queue_telemetry", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.RawObservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IngestOffset")
                        .HasColumnType("text")
                        .HasColumnName("ingest_offset");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("PayloadReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_reference");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt");

                    b.HasIndex("PayloadReference")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("raw_observations", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.RetentionSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("ActionsDays")
                        .HasColumnType("integer")
                        .HasColumnName("actions_days");

                    b.Property<int?>("AuditRecordsDays")
                        .HasColumnType("integer")
                        .HasColumnName("audit_records_days");

                    b.Property<int?>("ClassificationsDays")
                        .HasColumnType("integer")
                        .HasColumnName("classifications_days");

                    b.Property<int?>("DeadLetteredQueueMessagesDays")
                        .HasColumnType("integer")
                        .HasColumnName("dead_lettered_queue_messages_days");

                    b.Property<int?>("DecisionsDays")
                        .HasColumnType("integer")
                        .HasColumnName("decisions_days");

                    b.Property<int?>("EventsDays")
                        .HasColumnType("integer")
                        .HasColumnName("events_days");

                    b.Property<int?>("ExpiredAdminSessionsDays")
                        .HasColumnType("integer")
                        .HasColumnName("expired_admin_sessions_days");

                    b.Property<int?>("IncidentsDays")
                        .HasColumnType("integer")
                        .HasColumnName("incidents_days");

                    b.Property<DateTimeOffset?>("LastCycleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_cycle_at");

                    b.Property<string>("LastCycleCountsJson")
                        .HasColumnType("text")
                        .HasColumnName("last_cycle_counts_json");

                    b.Property<int?>("RawObservationsDays")
                        .HasColumnType("integer")
                        .HasColumnName("raw_observations_days");

                    b.Property<DateTimeOffset?>("SeededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seeded_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("retention_settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_retention_settings_fixed_id", "id = 1");
                        });
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.SourceOffsetRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text")
                        .HasColumnName("source_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("SourceId", "Key");

                    b.ToTable("source_offsets", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.SourceRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceType")
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActionRecordRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.ActionProviderRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminRecoveryCodeRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.AdminUserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminSessionRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.AdminUserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminTotpSecretRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.AdminUserRow", null)
                        .WithOne()
                        .HasForeignKey("Viegard.Persistence.Postgres.Model.AdminTotpSecretRow", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminUserPreferencesRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.AdminUserRow", null)
                        .WithOne()
                        .HasForeignKey("Viegard.Persistence.Postgres.Model.AdminUserPreferencesRow", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AdminWebAuthnCredentialRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.AdminUserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AuditRecordRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ClassificationRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.ClassifierRow", null)
                        .WithMany()
                        .HasForeignKey("ClassifierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.DecisionRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.PolicyRow", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.NormalizedEventRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.RawObservationRow", b =>
                {
                    b.HasOne("Viegard.Persistence.Postgres.Model.SourceRow", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
