// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viegard.Persistence.Postgres;

#nullable disable

namespace Viegard.Persistence.Postgres.Migrations
{
    [DbContext(typeof(ViegardDbContext))]
    partial class ViegardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ActionRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RollbackJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.AuditRecordRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.ClassificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassifierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer");

                    b.Property<double?>("Uncertainty")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SubjectId");

                    b.ToTable("classifications", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.CorrectionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectedCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("corrections", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.DecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuardrailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationId");

                    b.ToTable("decisions", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.IncidentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey", "State");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.NormalizedEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EntitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("RawObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RawObservationId");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueCounterRow", b =>
                {
                    b.Property<string>("QueueName")
                        .HasColumnType("text");

                    b.Property<long>("Abandoned")
                        .HasColumnType("bigint");

                    b.Property<long>("Completed")
                        .HasColumnType("bigint");

                    b.Property<long>("Enqueued")
                        .HasColumnType("bigint");

                    b.HasKey("QueueName");

                    b.ToTable("queue_counters", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueMessageRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("DeadLettered")
                        .HasColumnType("boolean");

                    b.Property<int>("DeliveryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QueueName", "DeadLettered", "LeasedUntil", "Id");

                    b.ToTable("queue_messages", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.QueueTelemetryRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("QueueName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeadLetterCount")
                        .HasColumnType("integer");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("InFlight")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OldestPendingEnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalAbandoned")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCompleted")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalEnqueued")
                        .HasColumnType("bigint");

                    b.HasKey("InstanceId", "QueueName");

                    b.ToTable("queue_telemetry", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.RawObservationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IngestOffset")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PayloadReference")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("raw_observations", (string)null);
                });

            modelBuilder.Entity("Viegard.Persistence.Postgres.Model.SourceOffsetRow", b =>
                {
                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SourceId", "Key");

                    b.ToTable("source_offsets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
